export const data = {
    labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
    datasets: [
      {
        label: 'TRANSACTIONS',
        fill: true,
        lineTension: 0.3,
        backgroundColor: '#FF993A',
        borderColor: '#FF993A',
        borderCapStyle: 'butt',
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: '#00B3FE',
        pointBackgroundColor: 'rgb(255, 255, 255)',
        pointBorderWidth: 5,
        pointHoverRadius: 5,
        pointHoverBackgroundColor: 'rgb(0, 0, 0)',
        pointHoverBorderColor: 'rgba(220, 220, 220,1)',
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [6575, 58999, 80, 8791, 5642, 55, 40],
      },
    
      {
        label: 'Exchange',
        fill: true,
        lineTension: 0.3,
        backgroundColor: '#00B3FE',
        borderColor: '#00B3FE',
        borderCapStyle: 'butt',
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'round',
        pointBorderColor: '#FF993A',
        pointBackgroundColor: 'rgb(255, 255, 255)',
        pointBorderWidth: 5,
        pointHoverRadius: 5,
        pointHoverBackgroundColor: '#00B3FE',
        pointHoverBorderColor: '#00B3FE',
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [45, 659, 290, 51, 26, 58435, 140],
      },
    //   {
    //     label: 'My Second dataset',
    //     fill: true,
    //     lineTension: 0.3,
    //     backgroundColor: 'rgba(184, 185, 210, .3)',
    //     borderColor: 'rgb(35, 26, 136)',
    //     borderCapStyle: 'butt',
    //     borderDash: [],
    //     borderDashOffset: 0.0,
    //     borderJoinStyle: 'miter',
    //     pointBorderColor: 'rgb(35, 26, 136)',
    //     pointBackgroundColor: 'rgb(255, 255, 255)',
    //     pointBorderWidth: 10,
    //     pointHoverRadius: 5,
    //     pointHoverBackgroundColor: 'rgb(0, 0, 0)',
    //     pointHoverBorderColor: 'rgba(220, 220, 220, 1)',
    //     pointHoverBorderWidth: 2,
    //     pointRadius: 1,
    //     pointHitRadius: 10,
    //     data: [28, 48, 40, 19, 86, 27, 90],
    //   },
    ],
  };
  